---
theme: jekyll-theme-minima
title: Antfield Creations
description: |-
  Antfield Creations: Artful Creativity.
  Dutch Chamber of commerce 84941634, 
  VAT id: NL004041441B67. Post address:
  Atelier Miereveld t.a.v. Antfield,
  Miereveldstraat 72, 3817RP Amersfoort.
  Site content ©Antfield Creations

markdown: gfm

plugins:
  - jekyll-feed
  - jekyll-seo-tag
