---
theme: jekyll-theme-minimal
title: Antfield Creations
description: |
  Artful Creativity.
  <br>
  <img src=/static/img/logo-centered.svg style="width: 50%;"></img>
  <br>
  KvK: 84941634
  <br>
  BTW id: NL004041441B67 
  <br>
  Vestigingsnummer 000051027410
  <br>
  rein@vantveer.me
  <br>
  <br>
  Postadres:
  <br>
  Miereveldstraat 72
  <br>
  3817RP Amersfoort
  <br>
  <br>
  Site content © Antfield Creations
markdown: gfm
